### ISSUE TITLE
Loading (old) version of metadata documents will not work.

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/frontend-collection#10]
**Describe the bug**
When viewing metadata documents, the current version of the document is displayed.
If you now click on the "Load" button, the document disappears. It does not matter whether you have selected another version or not.

**To Reproduce**
1. Select view of an existing metadata document
2. Switch to the 'Metadata Document' tab.
3. Click on 'Load.'
4. The metadata documents disappears

**Expected behavior**
The metadata document should be still displayed or (if selecting a different version) the selected version should be displayed.
![image](https://user-images.githubusercontent.com/14762686/219614119-41c8d6dd-85f7-433b-9792-2e1c33408de1.png)

**Comment by ThomasJejkal** [comment]
Same as in #11, can't be reproduced on demo.datamanager.kit.edu

**Comment by ThomasJejkal** [comment]
I'll close this issue for now. Please re-open if the error persists.
