### ISSUE TITLE
Optional values and drop down fields

### ISSUE THREAD

**Issue by reetuelzajoseph** [kit-data-manager/frontend-collection#15]
**Describe the bug**
When the optional field is a drop down menu, the first value is taken, even though this is not intended.

**To Reproduce**
1. Go to [https://matwerk.datamanager.kit.edu/repo-management.html](https://matwerk.datamanager.kit.edu/repo-management.html)
2. Click on Create Data Resource
3. Enter Title of the resource
4. while saving the Title will be saved with the type ALTERNATIVE_TITLE
5. All the current resources now, have ALTERNATIVE_TITLEs without having any other main TITLEs

**Expected behavior**
Either the type should not be saved so. Or there should be an entry which says Main Title or something similar.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 16.2

**Additional context**

**Comment by reetuelzajoseph** [comment]
One workaround is to include a blank item as the first item of the dropdown list

**Comment by ThomasJejkal** [comment]
Do you have an example for such an optional field? All cases I can imaging for the repo-management UI involve elements from a controlled list, which do not allow empty values, i.e., taking a contributor, which is per se optional, but as soon as you add a contributor, its contribution type becomes mandatory and as the UI cannot "guess" some proper contribution type, the first entry is selected as default.

**Comment by reetuelzajoseph** [comment]
Yes, first and foremost Title Type. It is optional. But the default is ALTERNATIVE_TiTLE. How can we save something of the type main title and not ALTERNATIVE_TITLE (or rather not enter the Title Type at all)?

**Comment by ThomasJejkal** [comment]
There is no value "main title" in the DataCite Standard (see https://schema.datacite.org/meta/kernel-4.4/include/datacite-titleType-v4.xsd) But you are right, according to the standard, the title type is optional, which is currently not supported in frontend-collection and should be supported in the next version.
