### ISSUE TITLE
No reaction when no title is entered to save a data resource

### ISSUE THREAD

**Issue by reetuelzajoseph** [kit-data-manager/frontend-collection#16]
**Describe the bug**
Adding a title is not intuitive as the first entry doesn't appear on the interface. The first entry for a Title has to be added by additional pressing a + button. If someone misses this, they might try to save a data resource without adding any title. Then no error message is shown, the interface just doesn't do anything. When you close the extra window for creating a resource, the error failed to create a resource is displayed. But reason is not evident.

Go to https://matwerk.datamanager.kit.edu/repo-management.html
Click on Create Data Resource
Do not press the + button to add a title
Save the data resource
Nothing happens!
User is confused as he/she doesn't know what to do next.

Expected behaviour:

An error message should be displayed saying that the title is missing. Additionally displaying one title entry on the form to be filled would be good. The same goes to access rights.

Desktop (please complete the following information):

OS: MacOS
Browser Safari
Version 16.2

Additional context

**Comment by ThomasJejkal** [comment]
Unfortunately, this is an issue of the underlying jsonform library. If an array attribute, which 'title' is, requires at least one element, validation will fail if none is provided. As a consequence, no DataResource will be created, but also no error indicator is shown. Not sure if this can be easily fixed but I'll try.
