### ISSUE TITLE
Place holders for date while creating a data resource

### ISSUE THREAD

**Issue by reetuelzajoseph** [kit-data-manager/frontend-collection#18]
**Is your feature request related to a problem? Please describe.**
No indication of the format in which the date should be entered while registering a data resource in https://matwerk.datamanager.kit.edu/repo-management.html

**Describe the solution you'd like**
I think if the wrong format is entered the resource does not get registered. Placeholders that show the format of the date should be made present

**Comment by ThomasJejkal** [comment]
Agree, will be added in the next version of frontend-collection.
