### ISSUE TITLE
Not sure if it is a real bug or something to do with the file itself

### ISSUE THREAD

**Issue by reetuelzajoseph** [kit-data-manager/frontend-collection#21]
**Describe the bug**
In the MatWerk instance- https://matwerk.datamanager.kit.edu/schema-management.html, A schema called MeinTest is registered. It has two versions, and metadata documents can be validated against it. But it is not possible to view this schema. HTTP 200

This is the schema referred to in the documentation, while registering a new metadata document. So someone following the documentation will not be able view the schema.

![image](https://github.com/kit-data-manager/frontend-collection/assets/88380730/c58639d1-5435-4cd4-a0e0-7daf0c44e6c0)

**To Reproduce**
1. Go to https://matwerk.datamanager.kit.edu/schema-management.html
2. Click on the eye button or edit button near the published Schema MeinTest
3.  See error

**Expected behavior**
Possibility to view the json file

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser: Safari
 - Version 16.2

**Comment by ThomasJejkal** [comment]
Same answer as for #20. Not sure what happens here as a valid document is returned (which is also indicated by HTTP 200) but not shown. Might be solved by the next version, but I'll check a soon as the update happened.

**Comment by ThomasJejkal** [comment]
I'll close this issue for now. Please re-open if the error still persists.
