### ISSUE TITLE
Front End of Data Repository does not have information fields

### ISSUE THREAD

**Issue by reetuelzajoseph** [kit-data-manager/frontend-collection#24]
**Is your feature request related to a problem? Please describe.**
While registering a data resource, the definitions/descriptions of the fields to be filled are not available. For example, I was confused what should I write in the field for Publisher, as the data I was going to upload was not already published anywhere. Actually for base-repo, the meaning for this field is "the person or the entity publishing this information on the repository (base-repo)". Such information is available for the fronend of MetaStore, but not for base-repo, at least on the NFDI-MatWerk Data Repository

**Describe the solution you'd like**
Information/Description about the fields should appear beneath them/ or with an information (i) button.

**Additional context**
Image of the interface for data resource:
<img width="955" alt="image" src="https://github.com/kit-data-manager/frontend-collection/assets/88380730/952b1614-cbc0-4d9a-8274-a538ebc831ac">

vs 

Image for registering metadata for metadata schema:
<img width="672" alt="image" src="https://github.com/kit-data-manager/frontend-collection/assets/88380730/01d5cbb6-df43-47e9-8d95-93935063bfbc">

**Comment by ThomasJejkal** [comment]
Descriptions are also available for all fields of repo-management in the current main branch and will be available for all instances of frontend-collection after updating them.
