### ISSUE TITLE
Display detailed error messages from base-repo/metaStore in the message area

### ISSUE THREAD

**Issue by reetuelzajoseph** [kit-data-manager/frontend-collection#36]
**Is your feature request related to a problem? Please describe.**
Currently when there is an error, only the error number is displayed in the messaging service on the front-end. e.g. HTTP 403
It would be great if the responses from base-repo or metaStore are displayed to give more context.

**Describe the solution you'd like**
For example, when there is a mismatch in the metadata document and the schema, metaStore sends a detailed list with all the errors, which can be seen in the network activity. It would be great if this message can be directly displayed in the front-end. Then the user can see what exactly is wrong. Else this information is not conveyed to the user directly.

**Describe alternatives you've considered**
A pop-up window which shows the error with more information would also work.

**Comment by ThomasJejkal** [comment]
This should be fixed now.
