### ISSUE TITLE
Ingest new metadata document is no longer possible.

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/frontend-collection#6]
**Describe the bug**
When a new metadata document is submitted. Always 'Please validate/check both, Record Metadata and Metadata Document. ' appears.

**To Reproduce**
1. Create a new metadata document. 
2. Click on 'Validate'
3.Click on 'Submit'
4. See error even for valid records/documents

**Expected behavior**
Create a new metadata document.

**Hint**
Inside metadata-management.html the function 'getDocumentFromMonaco()' returns null because getValue() of left and right model is the same.

**Comment by ThomasJejkal** [comment]
I'll close this issue for now. Please re-open if the error persists.
