### ISSUE TITLE
Loses the baseUrl setting when switching between schema and metadata management.

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/frontend-collection#8]
**Describe the bug**
In branch demo_instance I enabled show baseUrl. When changing the setting and press reload
everything is fine. As soon as I switch from schema management to metadata management or vice versa, the setting is lost. 

**To Reproduce**
1. Go to 'Schema Management.'
2. Change baseUrl and press 'Reload'
3. Switch to 'Metadata Management' 
4. See old baseURL.

**Expected behavior**
Once changed, this setting should remain.

**Comment by ThomasJejkal** [comment]
I would guess it's a caching issue. Both pages import metastore.settings.js and they may use the same cache such that the schema page overwrites the reloaded settings from its own cache.

**Comment by ThomasJejkal** [comment]
I'll close this issue for now. Please re-open if the error persists.
